# Generated by Django 3.2 on 2021-05-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='being_delivered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='received',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='refund_requested',
        ),
        migrations.AddField(
            model_name='order',
            name='being_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
    ]
