# Generated by Django 3.2 on 2021-05-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default='pk0vvkszraimhqsuo04y', max_length=20, null=True),
        ),
    ]
