# Generated by Django 3.2 on 2021-05-31 11:19

import base.models.order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_order_ref_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='ourcustomer',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='sales',
            new_name='oursales',
        ),
        migrations.AlterField(
            model_name='customer',
            name='nin_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default=base.models.order.create_ref_code, max_length=20, null=True),
        ),
    ]
